version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_service
    ports:
      - "54321:5432"
    volumes:
      - ./storage/docker/db:/var/lib/postgresql/data
